<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <RootNamespace>Atelier.Framework.Testing</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Atelier.Framework.Testing.Contract\Atelier.Framework.Testing.Contract.csproj" />
    <ProjectReference Include="..\Atelier.Framework.Outcomes\Atelier.Framework.Outcomes.csproj" />
    <ProjectReference Include="..\Atelier.Framework.Observability\Atelier.Framework.Observability.csproj" />
  </ItemGroup>
</Project>
