<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <IsPackable>false</IsPackable>
        <Optimize>true</Optimize>
        <ServerGarbageCollection>false</ServerGarbageCollection>
        <ConcurrentGarbageCollection>false</ConcurrentGarbageCollection>
        <TieredCompilation>false</TieredCompilation>
        <TieredPGO>false</TieredPGO>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="BenchmarkDotNet" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\..\Atelier.Framework.Attributes\Atelier.Framework.Attributes.csproj" />
        <ProjectReference Include="..\..\..\Atelier.Framework.Primitives\Atelier.Framework.Primitives.csproj" />
        <ProjectReference Include="..\..\..\Atelier.Framework.Identity.Authorization\Atelier.Framework.Identity.Authorization.csproj" />
        <ProjectReference Include="..\..\..\Atelier.Framework.Requisitions\Atelier.Framework.Requisitions.csproj" />
    </ItemGroup>
</Project>
