<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)Generated</CompilerGeneratedFilesOutputPath>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <NoWarn>$(NoWarn);NU1510</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Atelier.Framework.Contract\Atelier.Framework.Contract.csproj" />
        <ProjectReference Include="..\Atelier.Framework.Attributes\Atelier.Framework.Attributes.csproj" />
        <ProjectReference Include="..\Atelier.Framework.Primitives\Atelier.Framework.Primitives.csproj" />
        <ProjectReference Include="..\Atelier.Framework.Context\Atelier.Framework.Context.csproj" />

        <ProjectReference Include="..\Atelier.Framework.Infrastructure\Atelier.Framework.Infrastructure.csproj" />
        <ProjectReference Include="..\Atelier.Framework.Outcomes\Atelier.Framework.Outcomes.csproj" />
        <ProjectReference Include="..\Atelier.Framework.Observability\Atelier.Framework.Observability.csproj" />
        <ProjectReference Include="..\Atelier.Framework.Strategy\Atelier.Framework.Strategy.csproj" />

        <ProjectReference Include="..\Atelier.Framework.Requisitions\Atelier.Framework.Requisitions.csproj" />
        <ProjectReference Include="..\Atelier.Framework.Resilience\Atelier.Framework.Resilience.csproj" />
        <ProjectReference Include="..\Atelier.Framework.Network.Generators\Atelier.Framework.Network.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
        <PackageReference Include="Templar.Net" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
        <PackageReference Include="Microsoft.Extensions.Logging" />
        <PackageReference Include="Microsoft.Extensions.Hosting" />
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
        <PackageReference Include="Grpc.Net.Client" />
        <PackageReference Include="Grpc.AspNetCore" />
        <PackageReference Include="Grpc.Core.Api" />
        <PackageReference Include="Google.Protobuf" />
        <PackageReference Include="Grpc.Tools" />
        <PackageReference Include="Castle.Core" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Templates\**\*.tpl" />
        <AdditionalFiles Include="Templates\**\*.tpl" />
        <EmbeddedResource Include="Compositors\**\*.tpl" />
        <CompilerVisibleProperty Include="RootNamespace" />
        <CompilerVisibleProperty Include="ProjectDir" />
    </ItemGroup>
</Project>