<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Atelier.Build</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <PackAsTool>true</PackAsTool>
    <ToolCommandName>smash</ToolCommandName>
    <PackageId>Atelier.Build</PackageId>
    <Description>The Atelier build system - declarative boutique compilation</Description>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" />
    <PackageReference Include="System.Reflection.MetadataLoadContext" />
    <PackageReference Include="YamlDotNet" />
    <PackageReference Include="Spectre.Console" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="Microsoft.Build" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.Build.Locator" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Vice" />
    <PackageReference Include="Templar.Net" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Atelier.Framework.Testing\Atelier.Framework.Testing.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Templates\**\*.tpl" />
    <AdditionalFiles Include="Templates\**\*.tpl" />
    <CompilerVisibleProperty Include="RootNamespace" />
    <CompilerVisibleProperty Include="ProjectDir" />
  </ItemGroup>


</Project>
