<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <IsPackable>false</IsPackable>
        <Optimize>true</Optimize>
        <ServerGarbageCollection>false</ServerGarbageCollection>
        <ConcurrentGarbageCollection>false</ConcurrentGarbageCollection>
        <TieredCompilation>false</TieredCompilation>
        <TieredPGO>false</TieredPGO>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="BenchmarkDotNet" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\..\Atelier.Framework.Outcomes\Atelier.Framework.Outcomes.csproj" />
    </ItemGroup>
</Project>
