<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <ProjectReference Include="..\Atelier.Facilities.Cache\Atelier.Facilities.Cache.csproj" />
        <ProjectReference Include="..\Atelier.Framework.Facility\Atelier.Framework.Facility.csproj" />
        <ProjectReference Include="..\Atelier.Framework.Offering\Atelier.Framework.Offering.csproj" />
        <ProjectReference Include="..\Atelier.Framework.Host.Execution\Atelier.Framework.Host.Execution.csproj" />
        <ProjectReference Include="..\Atelier.Framework.Context\Atelier.Framework.Context.csproj" />
        <ProjectReference Include="..\Atelier.Framework.Network\Atelier.Framework.Network.csproj" />
        <ProjectReference Include="..\Atelier.Framework.Infrastructure\Atelier.Framework.Infrastructure.csproj" />
        <ProjectReference Include="..\Atelier.Framework.Observability\Atelier.Framework.Observability.csproj" />
        <ProjectReference Include="..\Atelier.Framework.Outcomes\Atelier.Framework.Outcomes.csproj" />
        <ProjectReference Include="..\Atelier.Framework.Requisitions\Atelier.Framework.Requisitions.csproj" />
    </ItemGroup>
</Project>
