<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
        <CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)Generated</CompilerGeneratedFilesOutputPath>
        <NoWarn>$(NoWarn);NU1510</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Atelier.Framework.Infrastructure\Atelier.Framework.Infrastructure.csproj" />

        <FrameworkReference Include="Microsoft.AspNetCore.App" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    </ItemGroup>
</Project>
