{{ usings }}
{{ assemblyLoaderCall }}
{{ builderCreation }}
{{ kestrelConfiguration }}
{{ instanceIdAndMetrics }}
{{ coreServiceRegistration }}
{{ infrastructureSetup }}
{{ autoDiscovery }}
{{ fallbackServiceRegistrations }}
{{ explicitServiceRegistrations }}
{{ capabilities }}
{{ healthChecks }}
{{ customServiceConfiguration }}
{{ appBuilding }}
{{ attacheHostConfiguration }}
{{ boutiqueManifestCreation }}
{{ endpointMapping }}
{{ lifecycleHandlers }}
{{ runCommand }}
