<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)Generated</CompilerGeneratedFilesOutputPath>
        <NoWarn>$(NoWarn);ATELIER0200;ATELIER1101</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Atelier.Framework.Outcomes\Atelier.Framework.Outcomes.csproj" />
        <ProjectReference Include="..\Atelier.Framework.Requisitions\Atelier.Framework.Requisitions.csproj" />
        <ProjectReference Include="..\Atelier.Framework.Testing.Contract\Atelier.Framework.Testing.Contract.csproj" PrivateAssets="all" />
    </ItemGroup>
</Project>
