<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>preview</LangVersion>
        <IsRoslynComponent>true</IsRoslynComponent>
        <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
        <Nullable>enable</Nullable>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <NoWarn>$(NoWarn);RS1041;RS2008</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" PrivateAssets="all" />
        <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" PrivateAssets="all" />
        <PackageReference Include="Templar.Net" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Atelier.Framework.Requisitions.Generators\Atelier.Framework.Requisitions.Generators.csproj"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="true" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Templates\**\*.tpl" />
        <AdditionalFiles Include="Templates\**\*.tpl" />
        <EmbeddedResource Include="Compositors\**\*.tpl" />
        <CompilerVisibleProperty Include="RootNamespace" />
        <CompilerVisibleProperty Include="ProjectDir" />
    </ItemGroup>

    <PropertyGroup>
        <GetTargetPathDependsOn>$(GetTargetPathDependsOn);GetDependencyTargetPaths</GetTargetPathDependsOn>
    </PropertyGroup>

    <Target Name="GetDependencyTargetPaths" DependsOnTargets="ResolveReferences">
        <ItemGroup>
            <TargetPathWithTargetPlatformMoniker
                Include="@(ReferencePath->WithMetadataValue('FileName', 'Templar'))"
                IncludeRuntimeDependency="false" />
        </ItemGroup>
    </Target>
</Project>
