<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
        <CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)Generated</CompilerGeneratedFilesOutputPath>
        <IsRoslynComponent>true</IsRoslynComponent>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageId>Atelier.Framework.Analyzers</PackageId>
        <Description>Roslyn analyzers for Atelier Framework</Description>
        <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <NoWarn>$(NoWarn);RS1041;RS2008</NoWarn>
        <IncludeBuildOutput>false</IncludeBuildOutput>
        <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.Analyzers"/>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp"/>
        <PackageReference Include="System.Composition.AttributedModel"/>
    </ItemGroup>
    <ItemGroup>
        <None Include="$([MSBuild]::EnsureTrailingSlash('$(OutputPath)'))$(AssemblyName).dll"
              Pack="true"
              PackagePath="analyzers/dotnet/cs"
              Visible="false" />
    </ItemGroup>
</Project>